### ISSUE TITLE
Error with docker-compose

### ISSUE THREAD

**Issue by apvlv** [benyanke/docker-taiga#5]
Hello,
I get the following error while running docker-compose. Do you have a hint for me? Thanks!

`ERROR: for taiga  Cannot start service taiga: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/andrej/docker-taiga/conf.json\\\" to rootfs \\\"/var/lib/docker/overlay2/2544c5fae66066a603a421863f127ee060b2e10ccc0076aaa15995673fe5a526/merged\\\" at \\\"/var/lib/docker/overlay2/2544c5fae66066a603a421863f127ee060b2e10ccc0076aaa15995673fe5a526/merged/taiga/conf.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`

**Comment by ajira86** [comment]
seams to be more a problem with docker and filesystem than the image itself. are you working on windows ? perhaps this issue could help you ? https://github.com/docker/for-win/issues/982

**Comment by benyanke** [comment]
This is actually somewhat of a hack which I had to do. Conf.json is autogenerated, which mostly works, but I didn't have a chance to finish up the last few pieces of it for some quirks of our setup, so I added the option to mount it.

If you remove the volume altogether, and leave conf.json inside the container with no mount (ie - comment or remove the line adding it's volume), you will probably be fine.

On my backlog to do the real fix, at some point... (edit: 'real fix' now tracked in #6)

In the mean time, give that a try.

**Comment by apvlv** [comment]
Thank you, without the mount the containers are running now. I'm on Ubuntu 18.04 Server. I have a problem now, that I can curl the container itself via its internal IP 172.19.0.2 but not via the server host itself. But probably it's not a problem with your project, so this issue can be closed. Thank you!

**Comment by benyanke** [comment]
Yes - this is expected, it's designed to be used behind a loadbalancer container to handle TLS and such. Of course you can add port forward directives to the docker-compose file if you'd like to change that.
